# Generated by Django 2.1.7 on 2019-03-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tweet_tweetlike_tweetshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
