# Generated by Django 2.1.7 on 2019-03-02 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tweet_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=120)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='profileuser',
            name='avatar',
            field=models.ImageField(default='img/man.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='tweetcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tweet',
            name='comments',
            field=models.ManyToManyField(to='app.TweetComment'),
        ),
    ]
